### PR TITLE
Merge remote-tracking branch 'kiliman/master'

### LINKED ISSUE #177: Create `::` ligature
## Request preferences

* Weight requested: SSm Book mainly, but it would be nice to also have it for Book Italic, Medium and Medium Italic.

## Ligature description

A lot of ligature fonts have a ligature for `::` where the colons are just slightly closer together. I find that this really helps readability for C++ and Rust code, where it's used for namespacing, and it's also nice in some functional languages that use it as an operator such as F#. It shouldn't be that difficult to create, but unfortunately I have no idea how to create a new ligature for this myself in Glyphs, so I'm requesting it here. Here are some screenshots demonstrating this ligature in other fonts (first screenshot is Operator Mono SSm Lig, which does not feature it)

Operator Mono SSm Lig
Recursive Code
JetBrains Mono
PragmataPro
Cascadia Code
Fira Code

---

### Ligature variations 

Due to how development is handled, not all ligatures are created at the same time. However, we will get to them all eventually. If you would like to help us develop ligatures, please reach out to us via email at kiliman@gmail.com

#### Operator Mono

- [ ] XLight
- [ ] XLight Italic
- [ ] Light
- [ ] Light Italic
- [ ] Book
- [ ] Book Italic
- [ ] Medium
- [ ] Medium Italic
- [ ] Bold
- [ ] Bold Italic

#### Operator Mono SSm

- [ ] SSm Light
- [ ] SSm Light Italic
- [ ] SSm Book
- [ ] SSm Book Italic
- [x] SSm Medium
- [ ] SSm Medium Italic
- [ ] SSm Bold
- [ ] SSm Bold Italic

### PR DESCRIPTION
**Pull request by Jakob6174**
New Ligatures:
    - colon_colon
    - exclam_exclam
    - semicolon_semicolon
    - less_less
    - greater_greater
    - hyphen_equal (minus_equal)
    - asterisk_equal
    - slash_equal
    - less_slash_greater
    - less_less_equal
    - quotedbl_quotedbl_quotedbl
    - quotesingle_quotesingle_quotesingle
New Powerline Glyhps:
    - E0A1 (Powerline LN)
    - E0A2 (Powerline lock)
    - E0B1 (Powerline left soft divider)
    - E0B3 (Powerline right soft divider)

Features:
    - ss10 can be used to substitute 'x' for '×'. Eg 0×FF or 800×600
    - 'Equality Spaces' and 'Less-than/Greater-than Horizontal Bar' alternatives are included
    by default, and can be activated via ss11 and ss12 respectively.
    - Corrected and simplified features code to include the missing 'kern' feature for
    fraction numerator and denominator positioning.

Edited and repositioned some existing glyphs to be more consistent across font weights.
Created missing glyphs for other weights. Eg 'w_w_w.liga' and 'plus_equal.liga'

Closes #177, #147, #124

### CODE REVIEW

**Comment by kiliman** [comment]
Wow. Thanks for the PR. I'm actually on a plane flying back home. I'll review it when I can. 

I'm inviting you to the private source repo which should make it easier to add and modify ligature glyphs.

**Comment by Jakob6174** [comment]
Hey, Sounds great. I just need to make a critical correction.

**Comment by pkazmier** [comment]
Any more progress on getting this merged. Very excited for the additional ligatures!

**Comment by kiliman** [comment]
Thanks for the PR. These new ligatures look great!

**Pull request merged**
