### PR TITLE
Operator Mono Book and Light fonts support

### PR DESCRIPTION
**Pull request by yamenarahman**

### CODE REVIEW

**Comment by kiliman** [comment]
@yamenarahman Thanks for the pull request. Although technically this does add the ligatures to the Book and Light weights, since you are using the existing Medium weight ligatures, they probably stand out too much against the lighter weight characters. 

I've made some enhancements to the extraction process so it will take less time to create the ligatures for each weight. These ligatures will look right at home with the rest of the font. I should have these done soon.

Thanks again for taking the time to contribute. It's been awesome the feedback that I've gotten.

**Comment by yamenarahman** [comment]
I've used the existed ligatures as it's not making that huge difference. Here is Book font with Medium ligatures.
screenshot from 2017-09-13 14-44-56

**Comment by kiliman** [comment]
Yeah, it's not as bad as I thought it would be. But here are some ligatures for the Book weight.

screen shot 2017-09-13 at 2 37 57 pm

**Comment by storskegg** [comment]
@kiliman @yamenarahman Thank you both for the work you've put into this. I've been thinking, for some time, that it'd be wonderful to just include the Fira Code ligatures in the Operator Mono font. I haven't had time to grok everything font, so I appreciate the work you've both been putting into this. (It's silly how much impact a font can have, isn't it?)

**Comment by yamenarahman** [comment]
It's so funny that I returned back to sublime after yesterday's release, sublime doesn't support font ligatures yet but I've to return because I use Laravel and its blade template engine which vscode really sucks in supporting it.

**Comment by kiliman** [comment]
I've pushed Operator Mono SSm Book and Medium weights (including italics).

Definitely try those and let me know what you think.

**Comment by drod3763** [comment]
I don't have the ScreenSmart version of Operator Mono. Any chance we will get ligatures for the regular version?

**Comment by kiliman** [comment]
Yes, I plan on doing the other versions as well. It takes about 30 minutes now to do each weight.

**Comment by carlevison** [comment]
Waiting patiently for Operator Mono Book, any time frame for when we can expect it?

**Comment by johnemau** [comment]
I would love to see light font support, is this PR dead?

**Comment by kiliman** [comment]
Yes. This is an old PR. It simply merged the Medium weight ligatures into the Book and Light weights.

I have finished true Book weight ligatures. I still need to do the Light weight.

Sorry for the delay.

**Comment by jdelman** [comment]
+1 for Operator Mono Light/Light Italic support. Willing to donate hard $$$ if necessary!

**Pull request closed without merging**
