### PR TITLE
add less_hyphen_greater ligature

### PR DESCRIPTION
**Pull request by CandySunPlus**
add less_hyphen_greater ligature

### CODE REVIEW

**Comment by kiliman** [comment]
Hi @CandySunPlus. Thanks for the PR, but may I ask how you created this?

**Comment by CandySunPlus** [comment]
I just add less_hyphen_greater.liga with glyphs based my ssm font and use extract.sh to generate the xml files

**Comment by mskelton** [comment]
This is a lot of file changes.  Can you remove all the changes that aren't required (i.e. trailing newline added to a bunch of the files).

**Comment by kiliman** [comment]
This looks really nice, however, I need you to update the actual source Glyphs file instead of updating the generated fonts. In Glyphs, we use components (existing glyphs) to build up the ligature. 

Here is your ligature composed of one path
image

Using components (less and greater are existing glyphs, we add hyphen, decompose and stretch). We overlap and Glyphs will remove the overlap during export. Also notice that I made the horizontal hint the width of the actual ligature.
image

By using existing components, it simplifies the generated font, ensuring proper hinting, etc. Also when generating the italic ligature, you can simply copy the glyph to the italic font, and Glyphs will use the italic version of the component automatically. The only thing you would need to do is select any existing paths and skew them 11 degrees.

image

I will add you to the private operator-mono-lig-source repo. Unfortunately I'm going to have to ask you to recreate your ligature in the source Glyphs file. Commit your changes and I will extract and push the ligatures out.

Thanks for your help.

**Comment by CandySunPlus** [comment]
where is the operator-mono-lig-source repo

**Comment by kiliman** [comment]
It's a private repo. I sent you an invite. You should have received an email.

**Comment by CandySunPlus** [comment]
> It's a private repo. I sent you an invite. You should have received an email.

I have a problem with my mailbox. Can you re-initiate the invitation?

**Comment by kiliman** [comment]
Here's the link.

https://github.com/kiliman/operator-mono-lig-source/invitations

**Pull request closed without merging**
